In [1]:
%%html
<style type='text/css'>
.CodeMirror{
    font-size: 18px;
}

div.output_area pre {
    font-size: 16px;
}
</style>

In [2]:
import numpy as np
print(np.__version__)

1.20.3


# 1. Cơ bản về mảng Numpy

## 1.1. Khởi tạo mảng

In [5]:
a = [5,3,8,9,1000]

**Hàm `np.array()`**

In [12]:
???

array([   5,    3,    8,    9, 1000])

In [7]:
# Khởi tạo và ép kiểu
a1 = np.array(a, ???)

a1

array([   5.,    3.,    8.,    9., 1000.], dtype=float32)

In [ ]:
# Tạo ra một bản copy từ một array
a2 = np.array(a1)
print(a2)
print(a1)

In [ ]:
# Thử thay đổi giá trị ở một mảng: không ảnh hưởng mảng kia
???

**Tùy chỉnh số thập phân và kiểu in**

In [26]:
x = [4.123456789123456789, 0.00012345678912, 
     25, 36, 17,20,22,23,25,27,34, 23, 21, 19, 24, 25, 27, 
     29, 28, 26, 29, 25, 34,20,22,23,25]

# Ép kiểu bằng hàm 'astype()'
x1 = ???

print(x1)

[4.1234567891e+00 1.2345678912e-04 2.5000000000e+01 ... 2.2000000000e+01
 2.3000000000e+01 2.5000000000e+01]


In [27]:
# Một số hàm tùy chỉnh
np.set_printoptions(precision=3) # chỉ in 3 chữ số thập phân
np.set_printoptions(threshold=10)# chỉ in tối đa 20 phần tử của mảng
np.set_printoptions(suppress=True) # không dùng scientific notation

In [29]:
print(x1)

[ 4.12346  0.00012 25.      ... 22.      23.      25.     ]


**Hàm `np.asarray()`**

In [13]:
a3 = np.asarray(a).astype(np.int16)
a3

array([   5,    3,    8,    9, 1000], dtype=int16)

**Nếu khởi tạo với `np.asarray()` từ một `array` khác**

In [9]:
a4 = np.asarray(a3)
a4[-1] = 1
print(a3)

[5 3 8 9 1]


In [10]:
print(a3)

[5 3 8 9 1]


In [14]:
# Lưu ý: list cũ không bị tác động
print(a)

[5, 3, 8, 9, 1000]


## 1.2. Mảng nhiều chiều

**Khởi tạo mảng nhiều chiều**

In [30]:
# Mảng 2 chiều
b = [[4,5,6], 
     [7,8,9], 
     [10,15,18], 
     [1000,2000,3000]
    ]
b1 = np.array(b)
b1

array([[   4,    5,    6],
       [   7,    8,    9],
       [  10,   15,   18],
       [1000, 2000, 3000]])

In [31]:
# Mảng 3 chiều
c = [[[4,5,6], [7,8,9], [10,15,18], [1000,2000,3000]],
     [[25,36,17], [20,22,23], [25,27,34], [23,21,19]]
    ]
c1 = np.asarray(c)
c1

array([[[   4,    5,    6],
        [   7,    8,    9],
        [  10,   15,   18],
        [1000, 2000, 3000]],

       [[  25,   36,   17],
        [  20,   22,   23],
        [  25,   27,   34],
        [  23,   21,   19]]])

**Kiểm tra kích thước, số chiều của mảng**
- shape
- ndim
- size

In [35]:
???

(2, 4, 3)
3
24


## 1.3. Truy cập vào mảng

**Truy cập vào vị trí theo chỉ số** <br>
(Lưu ý: chỉ số bắt đầu từ 0)

In [53]:
# Vào ma trận thứ 1 trong c1
???

array([[   4,    5,    6],
       [   7,    8,    9],
       [  10,   15,   18],
       [1000, 2000, 3000]])

In [54]:
# Lấy ra dòng 1 trong ma trận trên
???

array([7, 8, 9])

In [56]:
# Lấy ra giá trị cuối cùng ở dòng trên
???

9

In [57]:
# Thử thực hiện thay đổi giá trị
c1[0, 1, -1] = 100
print(c1)

[[[   4    5    6]
  [   7    8  100]
  [  10   15   18]
  [1000 2000 3000]]

 [[  25   36   17]
  [  20   22   23]
  [  25   27   34]
  [  23   21   19]]]


**Slicing**

In [58]:
c1[0,1:3]

array([[  7,   8, 100],
       [ 10,  15,  18]])

In [72]:
print(x1[0:7])

[ 4.12346  0.00012 25.      36.      17.      20.      22.     ]


In [73]:
# Slicing theo quy tắc 'start:stop:step'
???

[ 4.12346 25.      17.     ]


# 2. Một số hàm tính toán, sắp xếp

In [38]:
b1

array([[   4,    5,    6],
       [   7,    8,    9],
       [  10,   15,   18],
       [1000, 2000, 3000]])

## 2.1. Các phép toán học

**Một số các phép toán thông dụng**

In [43]:
b1 + 1

array([[   5,    6,    7],
       [   8,    9,   10],
       [  11,   16,   19],
       [1001, 2001, 3001]])

In [47]:
b1 - 2

array([[   2,    3,    4],
       [   5,    6,    7],
       [   8,   13,   16],
       [ 998, 1998, 2998]])

**Phép `Broadcasting`**

In [46]:
???

array([[   1,    3,    5],
       [   4,    6,    8],
       [   7,   13,   17],
       [ 997, 1998, 2999]])

## 2.2. Các hàm thống kê cơ bản

In [40]:
# Min/Max
print(np.min(b1))
print(np.max(b1))

[4 5 6]
[   6    9   18 3000]


In [42]:
# Mean, Median
???

[255.25 507.   758.25]
[ 8.5 11.5 13.5]


In [ ]:
# Variance, Standard Deviation
print(x1)
print(np.var(x1))
print(np.std(x1))

**Phân vị: `np.percentile`, `np.quantile`**

In [111]:
np.percentile(x1, [30, 70])

array([22. , 26.2])

In [112]:
np.quantile(x1, 0.5)

25.0

## 2.3. Sắp xếp tăng/giảm

In [49]:
# Sắp xếp tăng
np.sort([25, 36, 17, 20, 25])

array([17, 20, 25, 25, 36])

In [51]:
# Sắp xếp giảm
np.sort([25, 36, 17, 20, 25])[::-1]

array([36, 25, 25, 20, 17])

In [52]:
# Lấy ra index sẽ sắp xếp mảng
???

array([2, 3, 0, 4, 1], dtype=int64)

# 3. Một số khởi tạo đặc biệt

## 3.1. Khởi tạo mảng với 1 giá trị nào đó

- np.zeros(), np.zeros_like()
- np.ones(), np.ones_like()
- np.full()

In [80]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
np.ones_like(b1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [78]:
np.full((3,4), 100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

## 3.2. Khởi tạo chuỗi các giá trị

In [81]:
# arange(start, stop, step)
???


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
# linspace(start, stop, num)
???


array([3.5    , 3.86667, 4.23333, 4.6    , 4.96667, 5.33333, 5.7    ,
       6.06667, 6.43333, 6.8    ])

## 3.3. Khởi tạo ngẫu nhiên

**Tạo mảng số nguyên hoặc số thực**

In [87]:
np.random.rand()

0.13623432201904695

In [88]:
np.random.random((3,4))

array([[0.54414, 0.51818, 0.76686, 0.93385],
       [0.0897 , 0.19577, 0.99419, 0.23518],
       [0.23899, 0.6291 , 0.73495, 0.68834]])

In [91]:
np.random.randint(low=1, high=20, size=5)

array([ 6, 12,  8, 10,  2])

**Theo phân bố chuẩn**<br>
`np.random.normal(mean, standard-deviation, num)`

In [84]:
# Ví dụ: tạo 100 số ngẫu nhiên quanh giá trị 7 (std=2)
???

array([6.70826, 6.39161, 5.80931, ..., 9.54407, 5.13707, 7.42686])

In [85]:
# Thiết lập seed để cố định các giá trị tạo ra
???
np.random.normal(7, 2, 100)

array([ 4.47189, 10.05581,  5.05858, ...,  6.43596,  7.66336,  7.87412])

**Theo phân bố đều**<br>
`np.random.uniform(min, max, num)`

In [86]:
# Ví dụ: tạo 10 số ngẫu nhiên từ 2.2 đến 2.8
np.random.seed(30)
???

array([2.58649, 2.42845, 2.59783, 2.29819, 2.77756, 2.408  , 2.79505,
       2.34103, 2.55142, 2.44401])

**Luyện tập: tạo mảng số thực từ [-20, 50]**

In [ ]:
# Cách 1: dùng hàm rand()
???

In [ ]:
# Cách 2: dùng hàm uniform()
???

# 4. Tìm kiếm, so sánh và đếm

## 4.1. Tìm 1 giá trị hoặc so sánh với 1 ngưỡng

In [97]:
b1

array([[   4,    5,    6],
       [   7,    8,    9],
       [  10,   15,   18],
       [1000, 2000, 3000]])

In [94]:
b1 == 8

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [96]:
b1 >= 8

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [110]:
# Lấy ra các giá trị lớn hơn hoặc bằng 8
???

array([   8,    9,   10,   15,   18, 1000, 2000, 3000])

In [ ]:
# Lấy ra các giá trị chia hết cho 3
???


## 4.2. Đếm

**Đếm số lượng các giá trị thỏa điều kiện**

In [95]:
# Đếm các giá trị bằng 8
???

1

In [98]:
# Đếm các giá trị lớn hơn 8
???

7

**Đếm số lần xuất hiện của các giá trị bằng `np.unique()`**

In [104]:
ds = [25, 36, 17, 20, 23, 23, 25, 17, 36, 25]
np.unique(ds)

array([17, 20, 23, 25, 36])

In [105]:
???

(array([17, 20, 23, 25, 36]), array([2, 1, 2, 3, 2], dtype=int64))

In [106]:
# Lấy ra các kết quả
gia_tri, so_luong = ???
print(gia_tri)
print(so_luong)

[17 20 23 25 36]
[2 1 2 3 2]


**Luyện tập: lấy ra giá trị có số lần xuất hiện nhiều nhất (mode)?**

In [109]:
???

25