In [1]:
%%html
<style type='text/css'>
.CodeMirror{
    font-size: 18px;
}

div.output_area pre {
    font-size: 16px;
}
</style>

In [2]:
import numpy as np
print(np.__version__)

1.20.3


# 1. Cơ bản về mảng Numpy

## 1.1. Khởi tạo mảng

In [3]:
a = [5,3,8,9,1000]

**Hàm `np.array()`**

In [4]:
a0 = np.array(a)
a0

array([   5,    3,    8,    9, 1000])

In [5]:
# Khởi tạo và ép kiểu
a1 = np.array(a, dtype=np.float32)
a1

array([   5.,    3.,    8.,    9., 1000.], dtype=float32)

In [6]:
# Tạo ra một bản copy từ một array
a2 = np.array(a1)
print(a2)
print(a1)

[   5.    3.    8.    9. 1000.]
[   5.    3.    8.    9. 1000.]


In [7]:
a2[0] = 1
print(a2)
print(a1)

[   1.    3.    8.    9. 1000.]
[   5.    3.    8.    9. 1000.]


**Tùy chỉnh số thập phân và kiểu in**

In [9]:
x = [4.123456789123456789, 0.00012345678912, 
     25, 36, 17,20,22,23,25,27,34, 23, 21, 19, 24, 25, 27, 
     29, 28, 26, 29, 25, 34,20,22,23,25]

# Ép kiểu bằng hàm 'astype()'
x1 = np.array(x).astype(np.float64)
print(x1)

[4.12345679e+00 1.23456789e-04 2.50000000e+01 3.60000000e+01
 1.70000000e+01 2.00000000e+01 2.20000000e+01 2.30000000e+01
 2.50000000e+01 2.70000000e+01 3.40000000e+01 2.30000000e+01
 2.10000000e+01 1.90000000e+01 2.40000000e+01 2.50000000e+01
 2.70000000e+01 2.90000000e+01 2.80000000e+01 2.60000000e+01
 2.90000000e+01 2.50000000e+01 3.40000000e+01 2.00000000e+01
 2.20000000e+01 2.30000000e+01 2.50000000e+01]


In [12]:
# Một số hàm tùy chỉnh
np.set_printoptions(precision=3) # chỉ in 3 chữ số thập phân
np.set_printoptions(threshold=10)# chỉ in tối đa 20 phần tử của mảng
np.set_printoptions(suppress=True) # không dùng scientific notation

In [13]:
print(x1)

[ 4.123  0.    25.    ... 22.    23.    25.   ]


**Hàm `np.asarray()`**

In [13]:
a2 = np.asarray(a)
a2

array([   5,    3,    8,    9, 1000], dtype=int16)

In [9]:
a3 = np.asarray(a2)
a3[-1] = 1
print(a3)

[5 3 8 9 1]


In [10]:
print(a2)

[5 3 8 9 1]


In [14]:
# Lưu ý: list cũ không bị tác động
print(a)

[5, 3, 8, 9, 1000]


## 1.2. Mảng nhiều chiều

**Khởi tạo mảng nhiều chiều**

In [30]:
# Mảng 2 chiều
b = [[4,5,6], [7,8,9], [10,15,18], [1000,2000,3000]]
b1 = np.array(b)
b1

array([[   4,    5,    6],
       [   7,    8,    9],
       [  10,   15,   18],
       [1000, 2000, 3000]])

In [31]:
# Mảng 3 chiều
c = [[[4,5,6], [7,8,9], [10,15,18], [1000,2000,3000]],
     [[25,36,17], [20,22,23], [25,27,34], [23,21,19]]
    ]
c1 = np.array(c)
c1

array([[[   4,    5,    6],
        [   7,    8,    9],
        [  10,   15,   18],
        [1000, 2000, 3000]],

       [[  25,   36,   17],
        [  20,   22,   23],
        [  25,   27,   34],
        [  23,   21,   19]]])

**Kiểm tra kích thước, số chiều của mảng**
- shape
- ndim
- size

In [35]:
print(c1.shape)
print(c1.ndim)
print(c1.size)

(2, 4, 3)
3
24


## 1.3. Truy cập vào mảng

**Truy cập vào vị trí theo chỉ số** <br>
(Lưu ý: chỉ số bắt đầu từ 0)

In [53]:
c1[0]

array([[   4,    5,    6],
       [   7,    8,    9],
       [  10,   15,   18],
       [1000, 2000, 3000]])

In [54]:
c1[0,1]

array([7, 8, 9])

In [56]:
c1[0, 1, -1]

9

In [57]:
# Thử thực hiện thay đổi giá trị
c1[0, 1, -1] = 100
print(c1)

[[[   4    5    6]
  [   7    8  100]
  [  10   15   18]
  [1000 2000 3000]]

 [[  25   36   17]
  [  20   22   23]
  [  25   27   34]
  [  23   21   19]]]


**Slicing**

In [58]:
c1[0,1:3]

array([[  7,   8, 100],
       [ 10,  15,  18]])

In [72]:
print(x1[0:7])

[ 4.12346  0.00012 25.      36.      17.      20.      22.     ]


In [73]:
# Slicing theo quy tắc 'start:stop:step'
print(x1[0:5:2])

[ 4.12346 25.      17.     ]


# 2. Một số hàm tính toán, sắp xếp

## 2.1. Các phép toán học

In [38]:
b1

array([[   4,    5,    6],
       [   7,    8,    9],
       [  10,   15,   18],
       [1000, 2000, 3000]])

**Một số các phép toán thông dụng**

In [43]:
b1 + 1

array([[   5,    6,    7],
       [   8,    9,   10],
       [  11,   16,   19],
       [1001, 2001, 3001]])

In [47]:
b1 - 2

array([[   2,    3,    4],
       [   5,    6,    7],
       [   8,   13,   16],
       [ 998, 1998, 2998]])

**Phép `Broadcasting`**

In [46]:
b1 - np.array([3, 2, 1])

array([[   1,    3,    5],
       [   4,    6,    8],
       [   7,   13,   17],
       [ 997, 1998, 2999]])

## 2.2. Các hàm thống kê cơ bản

In [40]:
# Min/Max
print(np.min(b1, axis=0))
print(np.max(b1, axis=1))

[4 5 6]
[   6    9   18 3000]


In [42]:
# Mean, Median
print(np.mean(b1, axis=0))
print(np.median(b1, axis=0))

[255.25 507.   758.25]
[ 8.5 11.5 13.5]


In [16]:
# Variance, Standard Deviation
print(x1)
print(x1.var())
print(x1.std())

[ 4.123  0.    25.    ... 22.    23.    25.   ]
56.51386876006416
7.517570668777525


**Phân vị: `np.percentile`, `np.quantile`**

In [ ]:
np.percentile(x1, [30, 70])

In [ ]:
np.quantile(x1, 0.5)

## 2.3. Sắp xếp tăng/giảm

In [49]:
# Sắp xếp tăng
np.sort([25, 36, 17, 20, 25])

array([17, 20, 25, 25, 36])

In [51]:
# Sắp xếp giảm
np.sort([25, 36, 17, 20, 25])[::-1]

array([36, 25, 25, 20, 17])

In [52]:
# Lấy ra index sẽ sắp xếp mảng
np.argsort([25, 36, 17, 20, 25])

array([2, 3, 0, 4, 1], dtype=int64)

# 3. Một số khởi tạo đặc biệt

## 3.1. Khởi tạo mảng với 1 giá trị nào đó

- np.zeros(), np.zeros_like()
- np.ones(), np.ones_like()
- np.full()

In [80]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
np.ones_like(b1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [78]:
np.full((3,4), 100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

## 3.2. Khởi tạo chuỗi các giá trị

In [81]:
# arange(start, stop, step)
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
# linspace(start, stop, num)
np.linspace(3.5, 6.8, 10)

array([3.5    , 3.86667, 4.23333, 4.6    , 4.96667, 5.33333, 5.7    ,
       6.06667, 6.43333, 6.8    ])

## 3.3. Khởi tạo ngẫu nhiên

**Tạo mảng số nguyên hoặc số thực**

In [87]:
np.random.rand()

0.13623432201904695

In [88]:
np.random.random((3,4))

array([[0.54414, 0.51818, 0.76686, 0.93385],
       [0.0897 , 0.19577, 0.99419, 0.23518],
       [0.23899, 0.6291 , 0.73495, 0.68834]])

In [91]:
np.random.randint(low=1, high=20, size=5)

array([ 6, 12,  8, 10,  2])

**Theo phân bố chuẩn**<br>
`np.random.normal(mean, standard-deviation, num)`

In [84]:
np.random.normal(7, 2, 100)

array([6.70826, 6.39161, 5.80931, ..., 9.54407, 5.13707, 7.42686])

In [85]:
np.random.seed(30)
np.random.normal(7, 2, 100)

array([ 4.47189, 10.05581,  5.05858, ...,  6.43596,  7.66336,  7.87412])

**Theo phân bố đều**<br>
`np.random.uniform(min, max, num)`

In [86]:
np.random.seed(30)
np.random.uniform(2.2, 2.8, 10)

array([2.58649, 2.42845, 2.59783, 2.29819, 2.77756, 2.408  , 2.79505,
       2.34103, 2.55142, 2.44401])

**Luyện tập: tạo mảng số thực từ [-20, 50]**

In [22]:
# Cách 1: dùng hàm rand()
np.random.seed(10)
kq1 = np.random.rand(30)*70 - 20
print(kq1)

[ 33.992 -18.547  24.355 ...  15.92   25.528  22.073]


In [23]:
# Cách 2: dùng hàm uniform()
kq2 = np.random.uniform(-20, 50, 30)
kq2

array([36.366, 16.515, 43.605, ..., 11.941, 37.829, -2.404])

# 4. Tìm kiếm, so sánh và đếm

## 4.1. Tìm 1 giá trị hoặc so sánh với 1 ngưỡng

In [97]:
b1

array([[   4,    5,    6],
       [   7,    8,    9],
       [  10,   15,   18],
       [1000, 2000, 3000]])

In [94]:
b1 == 8

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [96]:
b1 >= 8

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# Lấy ra các giá trị chia hết cho 3
b1[(b1 % 3) == 0]

## 4.2. Đếm

**Đếm số lượng các giá trị thỏa điều kiện**

In [95]:
np.count_nonzero(b1 == 8)

1

In [98]:
np.count_nonzero(b1 > 8)

7

**Đếm số lần xuất hiện của các giá trị bằng `np.unique()`**

In [104]:
ds = [25, 36, 17, 20, 23, 23, 25, 17, 36, 25]
np.unique(ds)

array([17, 20, 23, 25, 36])

In [105]:
np.unique(ds, return_counts=True)

(array([17, 20, 23, 25, 36]), array([2, 1, 2, 3, 2], dtype=int64))

In [106]:
# Lấy ra các kết quả
gia_tri, so_luong = np.unique(ds, return_counts=True)
print(gia_tri)
print(so_luong)

[17 20 23 25 36]
[2 1 2 3 2]


**Luyện tập: lấy ra giá trị có số lần xuất hiện nhiều nhất (mode)?**

In [109]:
???

25